### PR TITLE
Serialize command sequence to enable last pause command.

### PR DESCRIPTION
**Pull request by kiwi-cam**
This is a recreation of #528 which I found issues and haven't been able to merge. Swtiches seem to work fine but my heater-cooler starts throwing errors:
```
Jun 18 11:24:09 homebridge[13979]: [Broadlink RM] Heat Pump setActive: 1
Jun 18 11:24:09 homebridge[13979]: [Broadlink RM] Looking up temperature hex codes for 23
Jun 18 11:24:09 homebridge[13979]: [Broadlink RM] 	Sending hex codes for temperature 23
Jun 18 11:24:09 homebridge[13979]: [Broadlink RM] 	Adding ON code first
Jun 18 11:24:09 homebridge[13979]: [Broadlink RM] Updated currentHeaterCoolerState to 2
Jun 18 11:24:09 homebridge[13979]: AssertionError [ERR_ASSERTION]: [ERROR]: Heat Pump sendData (HEX value is missing)
Jun 18 11:24:09 homebridge[13979]:     at module.exports (/usr/lib/node_modules/homebridge-broadlink-rm-pro/helpers/sendData.js:7:3)
Jun 18 11:24:09 homebridge[13979]:     at HeaterCoolerAccessory.performSend (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:91:7)
Jun 18 11:24:09 homebridge[13979]:     at HeaterCoolerAccessory.setActive (/usr/lib/node_modules/homebridge-broadlink-rm-pro/accessories/heater-cooler.js:430:16)
Jun 18 11:24:09 homebridge[13979]:     at HeaterCoolerAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:145:9)
Jun 18 11:24:09 homebridge[13979]:     at Active.emit (node:events:513:28)
Jun 18 11:24:09 homebridge[13979]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2596:16
Jun 18 11:24:09 homebridge[13979]:     at new Promise (<anonymous>)
Jun 18 11:24:09 homebridge[13979]:     at Active.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2594:14)
Jun 18 11:24:09 homebridge[13979]:     at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
Jun 18 11:24:09 homebridge[13979]:     at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
Jun 18 11:24:09 homebridge[13979]: Got SIGTERM, shutting down Homebridge...
Jun 18 11:24:10 homebridge[13979]: Got SIGTERM, shutting down child bridge process...
```

I wanted to re-open the PR as it seemed to have merit over the fixes in #520 and wanted a space to work through the issues.

@banboobee

### CODE REVIEW

**Comment by banboobee** [comment]
Hi kiwi-cam,

This PR #528 revised only 2 files as folllow, 

2320cf86562bce41ddb4e4c05b26c022e13c2945

But in your beta branch, more or less files are seemed to be updated.

**Comment by banboobee** [comment]
As I wrote to you in the reply of PR #528, #528 and #520 are mutually exclusive.

Revert #520 first.

 Also revert #519, since it is included in the following patch.

Then apply c74fe44de5a4363ad725bb4f737300ffca68d3f3

**Comment by kiwi-cam** [comment]
Hi @banboobee. I see you're looking into this - thanks. I did revert all the PRs and re-apply #528. I found the issue remained so re-revered that and applied #520 which was successful. Due to the complexity in conflicts I had to do this all via the command line so not much to show for it here.

It doesn't help that I've also cleaned up some linting errors which have added a lot of noise to the change logs.

The issue seems to be related to advanced hex config (pauses, repeats etc). I haven't had much time to investigate further but I did just pull all your recent changes and I'm still seeing the same issue.

**Comment by banboobee** [comment]
No, I'm not looking your issue. I don't know what the issue is.  I'm using this function almost a year without any issues.

I found the PR branch was scrapped, and that is a reason for further committing. Please keep outside of your repositories clean.

To repair the code, I had to purge all of conflicting codes, and lost the PR as a result. So, I had to salvage the PR to apply it. Now, this branch is based on most recent release, I guess.

Since all of my PRs are independent each other, I strongly recommend to try PR by PR.

**Pull request closed without merging**
