### PR TITLE
Optionally use arp instead of ping

### PR DESCRIPTION
**Pull request by mfkrause**
Some devices, like many older TVs, might block ping probes. Therefore the ping checks used to manage the switches will not work on those devices.
I've found a pretty good workaround to be using `arp` instead of `ping` in those cases. At least this works for every device in my network. I've added arp functionality as an optional setting which can be configured in the config (`pingUseArp`). When the arp command resolves the given IP address to a MAC address successfully, the device is deemed online.
Only works if the arp command is installed on the homebridge host machine, which should be the default though.

This uses the lightweight open source [node-arp](https://github.com/nekuz0r/node-arp) module.

### CODE REVIEW

**Comment by masterfordev** [comment]
This is very useful. I honestly didn't know about TV they're rejecting ping until now. But thanks for the contribution, surely some other user will also have this problem. 

Maybe you can add it to the beta @kiwi-cam for test it and check that it doesn't make issues to those of us who use ping.

**Comment by kiwi-cam** [comment]
Nicely implemented. My only concern is how reliable it is. Don't ARP tables typically have a TTL of 10-20 minutes. Meaning your test will continue to pass for up to 20 minutes after the TV is turned off?

How responsive have you found it?

**Comment by mfkrause** [comment]
Thanks.
I'm currently using a 2s frequency. When I manually turn on (or off) the device, it does sometimes take about 10 seconds to recognize that through the ARP table. So, it's not as responsive as ping probes, but still good enough.
As far as I can see, the node-arp module used a tiny hack which pings the IP address first before doing the ARP lookup (see line 43 [here](https://github.com/nekuz0r/node-arp/blob/master/lib/arp.js)). Even if the ping fails, this encourages the arp kernel to populate the table. I'm not too much into networking, but seems like this is what bypasses the long TTL.

**Comment by kiwi-cam** [comment]
@mfkrause  This has been merged and published in homebridge-broadlink-rm-pro@4.4.1-beta.2

Please test and confirm it functions as expected.

**Comment by mfkrause** [comment]
Can confirm it works as expected. Thanks for the quick merge!

**Comment by masterfordev** [comment]
Ping working fine from this side with Homebridge 1.2.5.

**Comment by kiwi-cam** [comment]
One last thing. I've updated the documentation too: https://broadlink.kiwicam.nz/#switch

**Pull request merged**
